FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Services.ChatBot/Services.ChatBot.csproj", "Services.ChatBot/"]

RUN dotnet restore "Services.ChatBot/Services.ChatBot.csproj"

COPY . .
WORKDIR "/src/Services.ChatBot"

EXPOSE 8080
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080", "--non-interactive"]