FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Services.Inventario/Services.Inventario.csproj", "Services.Inventario/"]
COPY ["Shared.Core/Shared.Core.csproj", "Shared.Core/"]
RUN dotnet restore "Services.Inventario/Services.Inventario.csproj"

COPY . .
WORKDIR "/src/Services.Inventario"

EXPOSE 8080
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080", "--non-interactive"]