FROM node:20-alpine
WORKDIR /app

# Copiamos solo los manifiestos primero para aprovechar el cache
COPY package*.json ./
RUN npm install

# Copiamos el resto del código
COPY . .

EXPOSE 3000
# Node 20 nativamente soporta hot-reload con --watch
CMD ["node", "--watch", "index.js"]