FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173
# Ajustamos para que Vite escuche en todas las interfaces de red
CMD ["npm", "run", "dev", "--", "--host"]