using System.Text.Json.Serialization;

namespace Services.Pagos.Models
{
    /// <summary>
    /// Represents the structure of a webhook request received from the Wompi payment gateway.
    /// This model is used to parse incoming notifications about transaction status changes.
    /// </summary>
    public class WompiWebhookRequest
    {
        /// <summary>
        /// Gets or sets the unique identifier for the transaction provided by Wompi.
        /// </summary>
        [JsonPropertyName("idTransaccion")]
        public long IdTransaccion { get; set; }

        /// <summary>
        /// Gets or sets the transaction reference, typically generated by the merchant.
        /// </summary>
        [JsonPropertyName("referencia")]
        public string Referencia { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the status of the transaction (e.g., "APPROVED", "DECLINED", "PENDING").
        /// </summary>
        [JsonPropertyName("estado")]
        public string Estado { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the amount of the transaction.
        /// </summary>
        [JsonPropertyName("monto")]
        public decimal Monto { get; set; }
    }
}