using System.Text.Json.Serialization;

namespace Services.Pagos.Models;

/// <summary>
/// Represents the response from the Wompi API containing the details of a generated payment link.
/// </summary>
public class WompiEnlaceResponse
{
    /// <summary>
    /// Gets or sets the unique identifier for the payment link generated by Wompi.
    /// </summary>
    [JsonPropertyName("idEnlace")]
    public long IdEnlace { get; set; }

    /// <summary>
    /// Gets or sets the URL of the payment link where the customer can complete the transaction.
    /// </summary>
    [JsonPropertyName("urlEnlace")]
    public string UrlEnlace { get; set; } = "";
}